#include "uri.h"

static uri_state_t  _init_out_states[256] = 
{
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_HAS_SCHEME, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR
};

static uri_state_t  _scheme_out_states[256] = 
{
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_HAS_PATH, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_SEEK_SOLIDUS,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_HAS_PATH,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR,
	URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR, URI_STATE_ERROR
};


uri_state_t 
uri_init(uri_t *uri, const char *uridata)
{
	uri->start = uri-end = uridata;
	return (uri->state = URI_STATE_INIT);
}

#define SCAN(s, c) while(*s && *s != c) s++

uri_state_t _uri_proceed(uri_t *uri)
{
	switch (uri->state)
	{
	case URI_STATE_INIT:
		SCAN(uri->end, ':');
		return (uri->state = _init_out_states[(unsigned char)(*uri->end)]);
	case URI_STATE_HAS_SCHEME:
		uri->start = uri->end++;
		SCAN(uri->end, '?');
		switch (_scheme_out_states[(unsigned char)(*uri->end)])
		{
		case URI_STATE_SEEK_SOLIDUS:
			uri->end++;
		}
	}
}
